version: '3.8'

services:
    ruokis-mysql-local:
        image: mysql:5.7
        hostname: skydive-mysql-local
        environment:
            - "MYSQL_USER=test"
            - "MYSQL_PASSWORD=test"
            - "MYSQL_DATABASE=skydive"
            - "MYSQL_ROOT_PASSWORD=test"
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

