/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.skydive.db.tables.records;


import fi.morabotti.skydive.db.enums.ActivityAccess;
import fi.morabotti.skydive.db.enums.ActivityType;
import fi.morabotti.skydive.db.tables.Activity;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityRecord extends TableRecordImpl<ActivityRecord> implements Record13<Long, String, String, ActivityType, String, ActivityAccess, Boolean, Boolean, Timestamp, Timestamp, Timestamp, Timestamp, Long> {

    private static final long serialVersionUID = -946640534;

    /**
     * Setter for <code>activity.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>activity.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>activity.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>activity.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>activity.token</code>.
     */
    public void setToken(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>activity.token</code>.
     */
    public String getToken() {
        return (String) get(2);
    }

    /**
     * Setter for <code>activity.type</code>.
     */
    public void setType(ActivityType value) {
        set(3, value);
    }

    /**
     * Getter for <code>activity.type</code>.
     */
    public ActivityType getType() {
        return (ActivityType) get(3);
    }

    /**
     * Setter for <code>activity.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>activity.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>activity.access</code>.
     */
    public void setAccess(ActivityAccess value) {
        set(5, value);
    }

    /**
     * Getter for <code>activity.access</code>.
     */
    public ActivityAccess getAccess() {
        return (ActivityAccess) get(5);
    }

    /**
     * Setter for <code>activity.club_only</code>.
     */
    public void setClubOnly(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>activity.club_only</code>.
     */
    public Boolean getClubOnly() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>activity.visible</code>.
     */
    public void setVisible(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>activity.visible</code>.
     */
    public Boolean getVisible() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>activity.start_date</code>.
     */
    public void setStartDate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>activity.start_date</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>activity.end_date</code>.
     */
    public void setEndDate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>activity.end_date</code>.
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>activity.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>activity.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>activity.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>activity.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>activity.club_id</code>.
     */
    public void setClubId(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>activity.club_id</code>.
     */
    public Long getClubId() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, ActivityType, String, ActivityAccess, Boolean, Boolean, Timestamp, Timestamp, Timestamp, Timestamp, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Long, String, String, ActivityType, String, ActivityAccess, Boolean, Boolean, Timestamp, Timestamp, Timestamp, Timestamp, Long> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Activity.ACTIVITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Activity.ACTIVITY.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Activity.ACTIVITY.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ActivityType> field4() {
        return Activity.ACTIVITY.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Activity.ACTIVITY.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ActivityAccess> field6() {
        return Activity.ACTIVITY.ACCESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return Activity.ACTIVITY.CLUB_ONLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Activity.ACTIVITY.VISIBLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Activity.ACTIVITY.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Activity.ACTIVITY.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return Activity.ACTIVITY.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return Activity.ACTIVITY.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field13() {
        return Activity.ACTIVITY.CLUB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityType component4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityAccess component6() {
        return getAccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getClubOnly();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getVisible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component13() {
        return getClubId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityType value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityAccess value6() {
        return getAccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getClubOnly();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getVisible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value13() {
        return getClubId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value3(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value4(ActivityType value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value6(ActivityAccess value) {
        setAccess(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value7(Boolean value) {
        setClubOnly(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value8(Boolean value) {
        setVisible(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value9(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value10(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value11(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value12(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value13(Long value) {
        setClubId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord values(Long value1, String value2, String value3, ActivityType value4, String value5, ActivityAccess value6, Boolean value7, Boolean value8, Timestamp value9, Timestamp value10, Timestamp value11, Timestamp value12, Long value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivityRecord
     */
    public ActivityRecord() {
        super(Activity.ACTIVITY);
    }

    /**
     * Create a detached, initialised ActivityRecord
     */
    public ActivityRecord(Long id, String title, String token, ActivityType type, String description, ActivityAccess access, Boolean clubOnly, Boolean visible, Timestamp startDate, Timestamp endDate, Timestamp createdAt, Timestamp deletedAt, Long clubId) {
        super(Activity.ACTIVITY);

        set(0, id);
        set(1, title);
        set(2, token);
        set(3, type);
        set(4, description);
        set(5, access);
        set(6, clubOnly);
        set(7, visible);
        set(8, startDate);
        set(9, endDate);
        set(10, createdAt);
        set(11, deletedAt);
        set(12, clubId);
    }
}
