/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.skydive.db.tables.records;


import fi.morabotti.skydive.db.enums.ActivityAccess;
import fi.morabotti.skydive.db.enums.ActivityType;
import fi.morabotti.skydive.db.tables.Activity;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityRecord extends TableRecordImpl<ActivityRecord> implements Record11<Long, String, ActivityType, String, ActivityAccess, Boolean, Timestamp, Timestamp, Timestamp, Timestamp, Long> {

    private static final long serialVersionUID = 89018031;

    /**
     * Setter for <code>activity.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>activity.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>activity.token</code>.
     */
    public void setToken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>activity.token</code>.
     */
    public String getToken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>activity.type</code>.
     */
    public void setType(ActivityType value) {
        set(2, value);
    }

    /**
     * Getter for <code>activity.type</code>.
     */
    public ActivityType getType() {
        return (ActivityType) get(2);
    }

    /**
     * Setter for <code>activity.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>activity.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>activity.access</code>.
     */
    public void setAccess(ActivityAccess value) {
        set(4, value);
    }

    /**
     * Getter for <code>activity.access</code>.
     */
    public ActivityAccess getAccess() {
        return (ActivityAccess) get(4);
    }

    /**
     * Setter for <code>activity.visible</code>.
     */
    public void setVisible(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>activity.visible</code>.
     */
    public Boolean getVisible() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>activity.start_date</code>.
     */
    public void setStartDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>activity.start_date</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>activity.end_date</code>.
     */
    public void setEndDate(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>activity.end_date</code>.
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>activity.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>activity.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>activity.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>activity.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>activity.club_id</code>.
     */
    public void setClubId(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>activity.club_id</code>.
     */
    public Long getClubId() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, ActivityType, String, ActivityAccess, Boolean, Timestamp, Timestamp, Timestamp, Timestamp, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Long, String, ActivityType, String, ActivityAccess, Boolean, Timestamp, Timestamp, Timestamp, Timestamp, Long> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Activity.ACTIVITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Activity.ACTIVITY.TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ActivityType> field3() {
        return Activity.ACTIVITY.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Activity.ACTIVITY.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ActivityAccess> field5() {
        return Activity.ACTIVITY.ACCESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return Activity.ACTIVITY.VISIBLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Activity.ACTIVITY.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Activity.ACTIVITY.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Activity.ACTIVITY.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return Activity.ACTIVITY.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return Activity.ACTIVITY.CLUB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityType component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityAccess component5() {
        return getAccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getVisible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component11() {
        return getClubId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityType value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityAccess value5() {
        return getAccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getVisible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getClubId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value2(String value) {
        setToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value3(ActivityType value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value5(ActivityAccess value) {
        setAccess(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value6(Boolean value) {
        setVisible(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value7(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value8(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value9(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value10(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord value11(Long value) {
        setClubId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityRecord values(Long value1, String value2, ActivityType value3, String value4, ActivityAccess value5, Boolean value6, Timestamp value7, Timestamp value8, Timestamp value9, Timestamp value10, Long value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivityRecord
     */
    public ActivityRecord() {
        super(Activity.ACTIVITY);
    }

    /**
     * Create a detached, initialised ActivityRecord
     */
    public ActivityRecord(Long id, String token, ActivityType type, String description, ActivityAccess access, Boolean visible, Timestamp startDate, Timestamp endDate, Timestamp createdAt, Timestamp deletedAt, Long clubId) {
        super(Activity.ACTIVITY);

        set(0, id);
        set(1, token);
        set(2, type);
        set(3, description);
        set(4, access);
        set(5, visible);
        set(6, startDate);
        set(7, endDate);
        set(8, createdAt);
        set(9, deletedAt);
        set(10, clubId);
    }
}
