/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.skydive.db.tables.records;


import fi.morabotti.skydive.db.tables.ClubPilotActivityParticipation;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClubPilotActivityParticipationRecord extends TableRecordImpl<ClubPilotActivityParticipationRecord> implements Record6<Long, Long, Long, Long, Timestamp, Timestamp> {

    private static final long serialVersionUID = -124505172;

    /**
     * Setter for <code>club_pilot_activity_participation.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>club_pilot_activity_participation.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>club_pilot_activity_participation.account_id</code>.
     */
    public void setAccountId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>club_pilot_activity_participation.account_id</code>.
     */
    public Long getAccountId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>club_pilot_activity_participation.activity_id</code>.
     */
    public void setActivityId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>club_pilot_activity_participation.activity_id</code>.
     */
    public Long getActivityId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>club_pilot_activity_participation.plane_id</code>.
     */
    public void setPlaneId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>club_pilot_activity_participation.plane_id</code>.
     */
    public Long getPlaneId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>club_pilot_activity_participation.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>club_pilot_activity_participation.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>club_pilot_activity_participation.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>club_pilot_activity_participation.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, Long, Long, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, Long, Long, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ClubPilotActivityParticipation.CLUB_PILOT_ACTIVITY_PARTICIPATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ClubPilotActivityParticipation.CLUB_PILOT_ACTIVITY_PARTICIPATION.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return ClubPilotActivityParticipation.CLUB_PILOT_ACTIVITY_PARTICIPATION.ACTIVITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return ClubPilotActivityParticipation.CLUB_PILOT_ACTIVITY_PARTICIPATION.PLANE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return ClubPilotActivityParticipation.CLUB_PILOT_ACTIVITY_PARTICIPATION.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return ClubPilotActivityParticipation.CLUB_PILOT_ACTIVITY_PARTICIPATION.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getActivityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getPlaneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getActivityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getPlaneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubPilotActivityParticipationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubPilotActivityParticipationRecord value2(Long value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubPilotActivityParticipationRecord value3(Long value) {
        setActivityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubPilotActivityParticipationRecord value4(Long value) {
        setPlaneId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubPilotActivityParticipationRecord value5(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubPilotActivityParticipationRecord value6(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubPilotActivityParticipationRecord values(Long value1, Long value2, Long value3, Long value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClubPilotActivityParticipationRecord
     */
    public ClubPilotActivityParticipationRecord() {
        super(ClubPilotActivityParticipation.CLUB_PILOT_ACTIVITY_PARTICIPATION);
    }

    /**
     * Create a detached, initialised ClubPilotActivityParticipationRecord
     */
    public ClubPilotActivityParticipationRecord(Long id, Long accountId, Long activityId, Long planeId, Timestamp createdAt, Timestamp deletedAt) {
        super(ClubPilotActivityParticipation.CLUB_PILOT_ACTIVITY_PARTICIPATION);

        set(0, id);
        set(1, accountId);
        set(2, activityId);
        set(3, planeId);
        set(4, createdAt);
        set(5, deletedAt);
    }
}
