/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.skydive.db.tables.records;


import fi.morabotti.skydive.db.enums.ClubActivityAccess;
import fi.morabotti.skydive.db.enums.ClubActivityType;
import fi.morabotti.skydive.db.tables.ClubActivity;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClubActivityRecord extends TableRecordImpl<ClubActivityRecord> implements Record10<Long, ClubActivityType, String, ClubActivityAccess, Boolean, Timestamp, Timestamp, Timestamp, Timestamp, Long> {

    private static final long serialVersionUID = 113254111;

    /**
     * Setter for <code>club_activity.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>club_activity.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>club_activity.type</code>.
     */
    public void setType(ClubActivityType value) {
        set(1, value);
    }

    /**
     * Getter for <code>club_activity.type</code>.
     */
    public ClubActivityType getType() {
        return (ClubActivityType) get(1);
    }

    /**
     * Setter for <code>club_activity.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>club_activity.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>club_activity.access</code>.
     */
    public void setAccess(ClubActivityAccess value) {
        set(3, value);
    }

    /**
     * Getter for <code>club_activity.access</code>.
     */
    public ClubActivityAccess getAccess() {
        return (ClubActivityAccess) get(3);
    }

    /**
     * Setter for <code>club_activity.visible</code>.
     */
    public void setVisible(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>club_activity.visible</code>.
     */
    public Boolean getVisible() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>club_activity.start_date</code>.
     */
    public void setStartDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>club_activity.start_date</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>club_activity.end_date</code>.
     */
    public void setEndDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>club_activity.end_date</code>.
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>club_activity.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>club_activity.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>club_activity.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>club_activity.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>club_activity.club_id</code>.
     */
    public void setClubId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>club_activity.club_id</code>.
     */
    public Long getClubId() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, ClubActivityType, String, ClubActivityAccess, Boolean, Timestamp, Timestamp, Timestamp, Timestamp, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, ClubActivityType, String, ClubActivityAccess, Boolean, Timestamp, Timestamp, Timestamp, Timestamp, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ClubActivity.CLUB_ACTIVITY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ClubActivityType> field2() {
        return ClubActivity.CLUB_ACTIVITY.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ClubActivity.CLUB_ACTIVITY.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ClubActivityAccess> field4() {
        return ClubActivity.CLUB_ACTIVITY.ACCESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return ClubActivity.CLUB_ACTIVITY.VISIBLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return ClubActivity.CLUB_ACTIVITY.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return ClubActivity.CLUB_ACTIVITY.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return ClubActivity.CLUB_ACTIVITY.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return ClubActivity.CLUB_ACTIVITY.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return ClubActivity.CLUB_ACTIVITY.CLUB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubActivityType component2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubActivityAccess component4() {
        return getAccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getVisible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getClubId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubActivityType value2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubActivityAccess value4() {
        return getAccess();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getVisible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getClubId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubActivityRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubActivityRecord value2(ClubActivityType value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubActivityRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubActivityRecord value4(ClubActivityAccess value) {
        setAccess(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubActivityRecord value5(Boolean value) {
        setVisible(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubActivityRecord value6(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubActivityRecord value7(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubActivityRecord value8(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubActivityRecord value9(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubActivityRecord value10(Long value) {
        setClubId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubActivityRecord values(Long value1, ClubActivityType value2, String value3, ClubActivityAccess value4, Boolean value5, Timestamp value6, Timestamp value7, Timestamp value8, Timestamp value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClubActivityRecord
     */
    public ClubActivityRecord() {
        super(ClubActivity.CLUB_ACTIVITY);
    }

    /**
     * Create a detached, initialised ClubActivityRecord
     */
    public ClubActivityRecord(Long id, ClubActivityType type, String description, ClubActivityAccess access, Boolean visible, Timestamp startDate, Timestamp endDate, Timestamp createdAt, Timestamp deletedAt, Long clubId) {
        super(ClubActivity.CLUB_ACTIVITY);

        set(0, id);
        set(1, type);
        set(2, description);
        set(3, access);
        set(4, visible);
        set(5, startDate);
        set(6, endDate);
        set(7, createdAt);
        set(8, deletedAt);
        set(9, clubId);
    }
}
