/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.skydive.db.tables.records;


import fi.morabotti.skydive.db.tables.Jump;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JumpRecord extends TableRecordImpl<JumpRecord> implements Record7<Long, Integer, Timestamp, Long, Long, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1288457360;

    /**
     * Setter for <code>jump.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>jump.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>jump.jump_height</code>.
     */
    public void setJumpHeight(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>jump.jump_height</code>.
     */
    public Integer getJumpHeight() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>jump.jump_time</code>.
     */
    public void setJumpTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>jump.jump_time</code>.
     */
    public Timestamp getJumpTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>jump.account_id</code>.
     */
    public void setAccountId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>jump.account_id</code>.
     */
    public Long getAccountId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>jump.activity_id</code>.
     */
    public void setActivityId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>jump.activity_id</code>.
     */
    public Long getActivityId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>jump.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>jump.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>jump.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>jump.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Integer, Timestamp, Long, Long, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Integer, Timestamp, Long, Long, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Jump.JUMP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Jump.JUMP.JUMP_HEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Jump.JUMP.JUMP_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Jump.JUMP.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Jump.JUMP.ACTIVITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Jump.JUMP.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Jump.JUMP.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getJumpHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getJumpTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getActivityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getJumpHeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getJumpTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getActivityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JumpRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JumpRecord value2(Integer value) {
        setJumpHeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JumpRecord value3(Timestamp value) {
        setJumpTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JumpRecord value4(Long value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JumpRecord value5(Long value) {
        setActivityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JumpRecord value6(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JumpRecord value7(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JumpRecord values(Long value1, Integer value2, Timestamp value3, Long value4, Long value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JumpRecord
     */
    public JumpRecord() {
        super(Jump.JUMP);
    }

    /**
     * Create a detached, initialised JumpRecord
     */
    public JumpRecord(Long id, Integer jumpHeight, Timestamp jumpTime, Long accountId, Long activityId, Timestamp createdAt, Timestamp deletedAt) {
        super(Jump.JUMP);

        set(0, id);
        set(1, jumpHeight);
        set(2, jumpTime);
        set(3, accountId);
        set(4, activityId);
        set(5, createdAt);
        set(6, deletedAt);
    }
}
