/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.skydive.db.tables.records;


import fi.morabotti.skydive.db.tables.PilotActivityParticipation;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PilotActivityParticipationRecord extends TableRecordImpl<PilotActivityParticipationRecord> implements Record7<Long, Boolean, Long, Long, Long, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1452759911;

    /**
     * Setter for <code>pilot_activity_participation.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>pilot_activity_participation.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>pilot_activity_participation.active</code>.
     */
    public void setActive(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>pilot_activity_participation.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>pilot_activity_participation.account_id</code>.
     */
    public void setAccountId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>pilot_activity_participation.account_id</code>.
     */
    public Long getAccountId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>pilot_activity_participation.activity_id</code>.
     */
    public void setActivityId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>pilot_activity_participation.activity_id</code>.
     */
    public Long getActivityId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>pilot_activity_participation.plane_id</code>.
     */
    public void setPlaneId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>pilot_activity_participation.plane_id</code>.
     */
    public Long getPlaneId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>pilot_activity_participation.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>pilot_activity_participation.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>pilot_activity_participation.deleted_at</code>.
     */
    public void setDeletedAt(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>pilot_activity_participation.deleted_at</code>.
     */
    public Timestamp getDeletedAt() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Boolean, Long, Long, Long, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Boolean, Long, Long, Long, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field2() {
        return PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION.ACTIVITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION.PLANE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION.DELETED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component2() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getActivityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getPlaneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value2() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getActivityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getPlaneId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PilotActivityParticipationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PilotActivityParticipationRecord value2(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PilotActivityParticipationRecord value3(Long value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PilotActivityParticipationRecord value4(Long value) {
        setActivityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PilotActivityParticipationRecord value5(Long value) {
        setPlaneId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PilotActivityParticipationRecord value6(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PilotActivityParticipationRecord value7(Timestamp value) {
        setDeletedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PilotActivityParticipationRecord values(Long value1, Boolean value2, Long value3, Long value4, Long value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PilotActivityParticipationRecord
     */
    public PilotActivityParticipationRecord() {
        super(PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION);
    }

    /**
     * Create a detached, initialised PilotActivityParticipationRecord
     */
    public PilotActivityParticipationRecord(Long id, Boolean active, Long accountId, Long activityId, Long planeId, Timestamp createdAt, Timestamp deletedAt) {
        super(PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION);

        set(0, id);
        set(1, active);
        set(2, accountId);
        set(3, activityId);
        set(4, planeId);
        set(5, createdAt);
        set(6, deletedAt);
    }
}
