/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.skydive.db.tables.records;


import fi.morabotti.skydive.db.tables.Plane;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlaneRecord extends TableRecordImpl<PlaneRecord> implements Record3<Long, String, Long> {

    private static final long serialVersionUID = 489065490;

    /**
     * Setter for <code>plane.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>plane.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>plane.license_number</code>.
     */
    public void setLicenseNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>plane.license_number</code>.
     */
    public String getLicenseNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>plane.club_id</code>.
     */
    public void setClubId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>plane.club_id</code>.
     */
    public Long getClubId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, String, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Plane.PLANE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Plane.PLANE.LICENSE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Plane.PLANE.CLUB_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getLicenseNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getClubId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLicenseNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getClubId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaneRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaneRecord value2(String value) {
        setLicenseNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaneRecord value3(Long value) {
        setClubId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlaneRecord values(Long value1, String value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlaneRecord
     */
    public PlaneRecord() {
        super(Plane.PLANE);
    }

    /**
     * Create a detached, initialised PlaneRecord
     */
    public PlaneRecord(Long id, String licenseNumber, Long clubId) {
        super(Plane.PLANE);

        set(0, id);
        set(1, licenseNumber);
        set(2, clubId);
    }
}
