/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.skydive.db.tables;


import fi.morabotti.skydive.db.DefaultSchema;
import fi.morabotti.skydive.db.Indexes;
import fi.morabotti.skydive.db.Keys;
import fi.morabotti.skydive.db.tables.records.ActivityParticipationRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityParticipation extends TableImpl<ActivityParticipationRecord> {

    private static final long serialVersionUID = 1913471864;

    /**
     * The reference instance of <code>activity_participation</code>
     */
    public static final ActivityParticipation ACTIVITY_PARTICIPATION = new ActivityParticipation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActivityParticipationRecord> getRecordType() {
        return ActivityParticipationRecord.class;
    }

    /**
     * The column <code>activity_participation.id</code>.
     */
    public final TableField<ActivityParticipationRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>activity_participation.account_id</code>.
     */
    public final TableField<ActivityParticipationRecord, Long> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>activity_participation.activity_id</code>.
     */
    public final TableField<ActivityParticipationRecord, Long> ACTIVITY_ID = createField("activity_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>activity_participation.created_at</code>.
     */
    public final TableField<ActivityParticipationRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>activity_participation.deleted_at</code>.
     */
    public final TableField<ActivityParticipationRecord, Timestamp> DELETED_AT = createField("deleted_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>activity_participation</code> table reference
     */
    public ActivityParticipation() {
        this(DSL.name("activity_participation"), null);
    }

    /**
     * Create an aliased <code>activity_participation</code> table reference
     */
    public ActivityParticipation(String alias) {
        this(DSL.name(alias), ACTIVITY_PARTICIPATION);
    }

    /**
     * Create an aliased <code>activity_participation</code> table reference
     */
    public ActivityParticipation(Name alias) {
        this(alias, ACTIVITY_PARTICIPATION);
    }

    private ActivityParticipation(Name alias, Table<ActivityParticipationRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActivityParticipation(Name alias, Table<ActivityParticipationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ActivityParticipation(Table<O> child, ForeignKey<O, ActivityParticipationRecord> key) {
        super(child, key, ACTIVITY_PARTICIPATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACTIVITY_PARTICIPATION_ACCOUNT_ID, Indexes.ACTIVITY_PARTICIPATION_FK_ACTIVITY_PARTICIPATION_ACTIVITY_ID, Indexes.ACTIVITY_PARTICIPATION_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ActivityParticipationRecord, Long> getIdentity() {
        return Keys.IDENTITY_ACTIVITY_PARTICIPATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ActivityParticipationRecord>> getKeys() {
        return Arrays.<UniqueKey<ActivityParticipationRecord>>asList(Keys.KEY_ACTIVITY_PARTICIPATION_ID, Keys.KEY_ACTIVITY_PARTICIPATION_ACCOUNT_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ActivityParticipationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ActivityParticipationRecord, ?>>asList(Keys.FK_ACTIVITY_PARTICIPATION_ACCOUNT_ID, Keys.FK_ACTIVITY_PARTICIPATION_ACTIVITY_ID);
    }

    public Account account() {
        return new Account(this, Keys.FK_ACTIVITY_PARTICIPATION_ACCOUNT_ID);
    }

    public Activity activity() {
        return new Activity(this, Keys.FK_ACTIVITY_PARTICIPATION_ACTIVITY_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityParticipation as(String alias) {
        return new ActivityParticipation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityParticipation as(Name alias) {
        return new ActivityParticipation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActivityParticipation rename(String name) {
        return new ActivityParticipation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActivityParticipation rename(Name name) {
        return new ActivityParticipation(name, null);
    }
}
