/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.skydive.db.tables;


import fi.morabotti.skydive.db.DefaultSchema;
import fi.morabotti.skydive.db.Indexes;
import fi.morabotti.skydive.db.Keys;
import fi.morabotti.skydive.db.tables.records.ClubPilotActivityParticipationRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClubPilotActivityParticipation extends TableImpl<ClubPilotActivityParticipationRecord> {

    private static final long serialVersionUID = 447189312;

    /**
     * The reference instance of <code>club_pilot_activity_participation</code>
     */
    public static final ClubPilotActivityParticipation CLUB_PILOT_ACTIVITY_PARTICIPATION = new ClubPilotActivityParticipation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClubPilotActivityParticipationRecord> getRecordType() {
        return ClubPilotActivityParticipationRecord.class;
    }

    /**
     * The column <code>club_pilot_activity_participation.id</code>.
     */
    public final TableField<ClubPilotActivityParticipationRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>club_pilot_activity_participation.account_id</code>.
     */
    public final TableField<ClubPilotActivityParticipationRecord, Long> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>club_pilot_activity_participation.club_activity_id</code>.
     */
    public final TableField<ClubPilotActivityParticipationRecord, Long> CLUB_ACTIVITY_ID = createField("club_activity_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>club_pilot_activity_participation.plane_id</code>.
     */
    public final TableField<ClubPilotActivityParticipationRecord, Long> PLANE_ID = createField("plane_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>club_pilot_activity_participation.created_at</code>.
     */
    public final TableField<ClubPilotActivityParticipationRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>club_pilot_activity_participation.deleted_at</code>.
     */
    public final TableField<ClubPilotActivityParticipationRecord, Timestamp> DELETED_AT = createField("deleted_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>club_pilot_activity_participation</code> table reference
     */
    public ClubPilotActivityParticipation() {
        this(DSL.name("club_pilot_activity_participation"), null);
    }

    /**
     * Create an aliased <code>club_pilot_activity_participation</code> table reference
     */
    public ClubPilotActivityParticipation(String alias) {
        this(DSL.name(alias), CLUB_PILOT_ACTIVITY_PARTICIPATION);
    }

    /**
     * Create an aliased <code>club_pilot_activity_participation</code> table reference
     */
    public ClubPilotActivityParticipation(Name alias) {
        this(alias, CLUB_PILOT_ACTIVITY_PARTICIPATION);
    }

    private ClubPilotActivityParticipation(Name alias, Table<ClubPilotActivityParticipationRecord> aliased) {
        this(alias, aliased, null);
    }

    private ClubPilotActivityParticipation(Name alias, Table<ClubPilotActivityParticipationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ClubPilotActivityParticipation(Table<O> child, ForeignKey<O, ClubPilotActivityParticipationRecord> key) {
        super(child, key, CLUB_PILOT_ACTIVITY_PARTICIPATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CLUB_PILOT_ACTIVITY_PARTICIPATION_ACCOUNT_ID, Indexes.CLUB_PILOT_ACTIVITY_PARTICIPATION_FK_CLUB_PILOT_ACTIVITY_PARTICIPATION_ACTIVITY_ID, Indexes.CLUB_PILOT_ACTIVITY_PARTICIPATION_FK_CLUB_PILOT_ACTIVITY_PARTICIPATION_PLANE_ID, Indexes.CLUB_PILOT_ACTIVITY_PARTICIPATION_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ClubPilotActivityParticipationRecord, Long> getIdentity() {
        return Keys.IDENTITY_CLUB_PILOT_ACTIVITY_PARTICIPATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ClubPilotActivityParticipationRecord>> getKeys() {
        return Arrays.<UniqueKey<ClubPilotActivityParticipationRecord>>asList(Keys.KEY_CLUB_PILOT_ACTIVITY_PARTICIPATION_ID, Keys.KEY_CLUB_PILOT_ACTIVITY_PARTICIPATION_ACCOUNT_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ClubPilotActivityParticipationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ClubPilotActivityParticipationRecord, ?>>asList(Keys.FK_CLUB_PILOT_ACTIVITY_PARTICIPATION_ACCOUNT_ID, Keys.FK_CLUB_PILOT_ACTIVITY_PARTICIPATION_ACTIVITY_ID, Keys.FK_CLUB_PILOT_ACTIVITY_PARTICIPATION_PLANE_ID);
    }

    public Account account() {
        return new Account(this, Keys.FK_CLUB_PILOT_ACTIVITY_PARTICIPATION_ACCOUNT_ID);
    }

    public ClubActivity clubActivity() {
        return new ClubActivity(this, Keys.FK_CLUB_PILOT_ACTIVITY_PARTICIPATION_ACTIVITY_ID);
    }

    public Plane plane() {
        return new Plane(this, Keys.FK_CLUB_PILOT_ACTIVITY_PARTICIPATION_PLANE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubPilotActivityParticipation as(String alias) {
        return new ClubPilotActivityParticipation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClubPilotActivityParticipation as(Name alias) {
        return new ClubPilotActivityParticipation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClubPilotActivityParticipation rename(String name) {
        return new ClubPilotActivityParticipation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClubPilotActivityParticipation rename(Name name) {
        return new ClubPilotActivityParticipation(name, null);
    }
}
