/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.skydive.db.tables;


import fi.morabotti.skydive.db.DefaultSchema;
import fi.morabotti.skydive.db.Indexes;
import fi.morabotti.skydive.db.Keys;
import fi.morabotti.skydive.db.tables.records.PilotActivityParticipationRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PilotActivityParticipation extends TableImpl<PilotActivityParticipationRecord> {

    private static final long serialVersionUID = -105658750;

    /**
     * The reference instance of <code>pilot_activity_participation</code>
     */
    public static final PilotActivityParticipation PILOT_ACTIVITY_PARTICIPATION = new PilotActivityParticipation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PilotActivityParticipationRecord> getRecordType() {
        return PilotActivityParticipationRecord.class;
    }

    /**
     * The column <code>pilot_activity_participation.id</code>.
     */
    public final TableField<PilotActivityParticipationRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>pilot_activity_participation.active</code>.
     */
    public final TableField<PilotActivityParticipationRecord, Boolean> ACTIVE = createField("active", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "");

    /**
     * The column <code>pilot_activity_participation.account_id</code>.
     */
    public final TableField<PilotActivityParticipationRecord, Long> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pilot_activity_participation.activity_id</code>.
     */
    public final TableField<PilotActivityParticipationRecord, Long> ACTIVITY_ID = createField("activity_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pilot_activity_participation.plane_id</code>.
     */
    public final TableField<PilotActivityParticipationRecord, Long> PLANE_ID = createField("plane_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pilot_activity_participation.created_at</code>.
     */
    public final TableField<PilotActivityParticipationRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>pilot_activity_participation.deleted_at</code>.
     */
    public final TableField<PilotActivityParticipationRecord, Timestamp> DELETED_AT = createField("deleted_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>pilot_activity_participation</code> table reference
     */
    public PilotActivityParticipation() {
        this(DSL.name("pilot_activity_participation"), null);
    }

    /**
     * Create an aliased <code>pilot_activity_participation</code> table reference
     */
    public PilotActivityParticipation(String alias) {
        this(DSL.name(alias), PILOT_ACTIVITY_PARTICIPATION);
    }

    /**
     * Create an aliased <code>pilot_activity_participation</code> table reference
     */
    public PilotActivityParticipation(Name alias) {
        this(alias, PILOT_ACTIVITY_PARTICIPATION);
    }

    private PilotActivityParticipation(Name alias, Table<PilotActivityParticipationRecord> aliased) {
        this(alias, aliased, null);
    }

    private PilotActivityParticipation(Name alias, Table<PilotActivityParticipationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> PilotActivityParticipation(Table<O> child, ForeignKey<O, PilotActivityParticipationRecord> key) {
        super(child, key, PILOT_ACTIVITY_PARTICIPATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PILOT_ACTIVITY_PARTICIPATION_ACCOUNT_ID, Indexes.PILOT_ACTIVITY_PARTICIPATION_FK_PILOT_ACTIVITY_PARTICIPATION_ACTIVITY_ID, Indexes.PILOT_ACTIVITY_PARTICIPATION_FK_PILOT_ACTIVITY_PARTICIPATION_PLANE_ID, Indexes.PILOT_ACTIVITY_PARTICIPATION_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PilotActivityParticipationRecord, Long> getIdentity() {
        return Keys.IDENTITY_PILOT_ACTIVITY_PARTICIPATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PilotActivityParticipationRecord>> getKeys() {
        return Arrays.<UniqueKey<PilotActivityParticipationRecord>>asList(Keys.KEY_PILOT_ACTIVITY_PARTICIPATION_ID, Keys.KEY_PILOT_ACTIVITY_PARTICIPATION_ACCOUNT_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PilotActivityParticipationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PilotActivityParticipationRecord, ?>>asList(Keys.FK_PILOT_ACTIVITY_PARTICIPATION_ACCOUNT_ID, Keys.FK_PILOT_ACTIVITY_PARTICIPATION_ACTIVITY_ID, Keys.FK_PILOT_ACTIVITY_PARTICIPATION_PLANE_ID);
    }

    public Account account() {
        return new Account(this, Keys.FK_PILOT_ACTIVITY_PARTICIPATION_ACCOUNT_ID);
    }

    public Activity activity() {
        return new Activity(this, Keys.FK_PILOT_ACTIVITY_PARTICIPATION_ACTIVITY_ID);
    }

    public Plane plane() {
        return new Plane(this, Keys.FK_PILOT_ACTIVITY_PARTICIPATION_PLANE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PilotActivityParticipation as(String alias) {
        return new PilotActivityParticipation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PilotActivityParticipation as(Name alias) {
        return new PilotActivityParticipation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PilotActivityParticipation rename(String name) {
        return new PilotActivityParticipation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PilotActivityParticipation rename(Name name) {
        return new PilotActivityParticipation(name, null);
    }
}
