/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.skydive.db;


import fi.morabotti.skydive.db.tables.Account;
import fi.morabotti.skydive.db.tables.Activity;
import fi.morabotti.skydive.db.tables.ActivityParticipation;
import fi.morabotti.skydive.db.tables.Club;
import fi.morabotti.skydive.db.tables.ClubAccount;
import fi.morabotti.skydive.db.tables.ClubPilotActivityParticipation;
import fi.morabotti.skydive.db.tables.ClubProfile;
import fi.morabotti.skydive.db.tables.Jump;
import fi.morabotti.skydive.db.tables.Plane;
import fi.morabotti.skydive.db.tables.Profile;
import fi.morabotti.skydive.db.tables.Session;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -225873929;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>account</code>.
     */
    public final Account ACCOUNT = fi.morabotti.skydive.db.tables.Account.ACCOUNT;

    /**
     * The table <code>activity</code>.
     */
    public final Activity ACTIVITY = fi.morabotti.skydive.db.tables.Activity.ACTIVITY;

    /**
     * The table <code>activity_participation</code>.
     */
    public final ActivityParticipation ACTIVITY_PARTICIPATION = fi.morabotti.skydive.db.tables.ActivityParticipation.ACTIVITY_PARTICIPATION;

    /**
     * The table <code>club</code>.
     */
    public final Club CLUB = fi.morabotti.skydive.db.tables.Club.CLUB;

    /**
     * The table <code>club_account</code>.
     */
    public final ClubAccount CLUB_ACCOUNT = fi.morabotti.skydive.db.tables.ClubAccount.CLUB_ACCOUNT;

    /**
     * The table <code>club_pilot_activity_participation</code>.
     */
    public final ClubPilotActivityParticipation CLUB_PILOT_ACTIVITY_PARTICIPATION = fi.morabotti.skydive.db.tables.ClubPilotActivityParticipation.CLUB_PILOT_ACTIVITY_PARTICIPATION;

    /**
     * The table <code>club_profile</code>.
     */
    public final ClubProfile CLUB_PROFILE = fi.morabotti.skydive.db.tables.ClubProfile.CLUB_PROFILE;

    /**
     * The table <code>jump</code>.
     */
    public final Jump JUMP = fi.morabotti.skydive.db.tables.Jump.JUMP;

    /**
     * The table <code>plane</code>.
     */
    public final Plane PLANE = fi.morabotti.skydive.db.tables.Plane.PLANE;

    /**
     * The table <code>profile</code>.
     */
    public final Profile PROFILE = fi.morabotti.skydive.db.tables.Profile.PROFILE;

    /**
     * The table <code>session</code>.
     */
    public final Session SESSION = fi.morabotti.skydive.db.tables.Session.SESSION;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            Activity.ACTIVITY,
            ActivityParticipation.ACTIVITY_PARTICIPATION,
            Club.CLUB,
            ClubAccount.CLUB_ACCOUNT,
            ClubPilotActivityParticipation.CLUB_PILOT_ACTIVITY_PARTICIPATION,
            ClubProfile.CLUB_PROFILE,
            Jump.JUMP,
            Plane.PLANE,
            Profile.PROFILE,
            Session.SESSION);
    }
}
