/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.skydive.db;


import fi.morabotti.skydive.db.tables.Account;
import fi.morabotti.skydive.db.tables.Session;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNT_ID = Indexes0.ACCOUNT_ID;
    public static final Index ACCOUNT_USERNAME = Indexes0.ACCOUNT_USERNAME;
    public static final Index SESSION_FK_SESSION_ACCOUNT = Indexes0.SESSION_FK_SESSION_ACCOUNT;
    public static final Index SESSION_ID = Indexes0.SESSION_ID;
    public static final Index SESSION_TOKEN = Indexes0.SESSION_TOKEN;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCOUNT_ID = Internal.createIndex("id", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.ID }, true);
        public static Index ACCOUNT_USERNAME = Internal.createIndex("username", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.USERNAME }, true);
        public static Index SESSION_FK_SESSION_ACCOUNT = Internal.createIndex("fk_session_account", Session.SESSION, new OrderField[] { Session.SESSION.ACCOUNT_ID }, false);
        public static Index SESSION_ID = Internal.createIndex("id", Session.SESSION, new OrderField[] { Session.SESSION.ID }, true);
        public static Index SESSION_TOKEN = Internal.createIndex("token", Session.SESSION, new OrderField[] { Session.SESSION.TOKEN }, true);
    }
}
