/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.skydive.db;


import fi.morabotti.skydive.db.tables.Account;
import fi.morabotti.skydive.db.tables.Activity;
import fi.morabotti.skydive.db.tables.ActivityParticipation;
import fi.morabotti.skydive.db.tables.Club;
import fi.morabotti.skydive.db.tables.ClubAccount;
import fi.morabotti.skydive.db.tables.ClubProfile;
import fi.morabotti.skydive.db.tables.Jump;
import fi.morabotti.skydive.db.tables.PilotActivityParticipation;
import fi.morabotti.skydive.db.tables.Plane;
import fi.morabotti.skydive.db.tables.Profile;
import fi.morabotti.skydive.db.tables.Session;
import fi.morabotti.skydive.db.tables.records.AccountRecord;
import fi.morabotti.skydive.db.tables.records.ActivityParticipationRecord;
import fi.morabotti.skydive.db.tables.records.ActivityRecord;
import fi.morabotti.skydive.db.tables.records.ClubAccountRecord;
import fi.morabotti.skydive.db.tables.records.ClubProfileRecord;
import fi.morabotti.skydive.db.tables.records.ClubRecord;
import fi.morabotti.skydive.db.tables.records.JumpRecord;
import fi.morabotti.skydive.db.tables.records.PilotActivityParticipationRecord;
import fi.morabotti.skydive.db.tables.records.PlaneRecord;
import fi.morabotti.skydive.db.tables.records.ProfileRecord;
import fi.morabotti.skydive.db.tables.records.SessionRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AccountRecord, Long> IDENTITY_ACCOUNT = Identities0.IDENTITY_ACCOUNT;
    public static final Identity<ActivityRecord, Long> IDENTITY_ACTIVITY = Identities0.IDENTITY_ACTIVITY;
    public static final Identity<ActivityParticipationRecord, Long> IDENTITY_ACTIVITY_PARTICIPATION = Identities0.IDENTITY_ACTIVITY_PARTICIPATION;
    public static final Identity<ClubRecord, Long> IDENTITY_CLUB = Identities0.IDENTITY_CLUB;
    public static final Identity<ClubAccountRecord, Long> IDENTITY_CLUB_ACCOUNT = Identities0.IDENTITY_CLUB_ACCOUNT;
    public static final Identity<ClubProfileRecord, Long> IDENTITY_CLUB_PROFILE = Identities0.IDENTITY_CLUB_PROFILE;
    public static final Identity<JumpRecord, Long> IDENTITY_JUMP = Identities0.IDENTITY_JUMP;
    public static final Identity<PilotActivityParticipationRecord, Long> IDENTITY_PILOT_ACTIVITY_PARTICIPATION = Identities0.IDENTITY_PILOT_ACTIVITY_PARTICIPATION;
    public static final Identity<PlaneRecord, Long> IDENTITY_PLANE = Identities0.IDENTITY_PLANE;
    public static final Identity<ProfileRecord, Long> IDENTITY_PROFILE = Identities0.IDENTITY_PROFILE;
    public static final Identity<SessionRecord, Long> IDENTITY_SESSION = Identities0.IDENTITY_SESSION;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> KEY_ACCOUNT_ID = UniqueKeys0.KEY_ACCOUNT_ID;
    public static final UniqueKey<AccountRecord> KEY_ACCOUNT_USERNAME = UniqueKeys0.KEY_ACCOUNT_USERNAME;
    public static final UniqueKey<ActivityRecord> KEY_ACTIVITY_ID = UniqueKeys0.KEY_ACTIVITY_ID;
    public static final UniqueKey<ActivityRecord> KEY_ACTIVITY_TOKEN = UniqueKeys0.KEY_ACTIVITY_TOKEN;
    public static final UniqueKey<ActivityParticipationRecord> KEY_ACTIVITY_PARTICIPATION_ID = UniqueKeys0.KEY_ACTIVITY_PARTICIPATION_ID;
    public static final UniqueKey<ActivityParticipationRecord> KEY_ACTIVITY_PARTICIPATION_ACCOUNT_ID = UniqueKeys0.KEY_ACTIVITY_PARTICIPATION_ACCOUNT_ID;
    public static final UniqueKey<ClubRecord> KEY_CLUB_ID = UniqueKeys0.KEY_CLUB_ID;
    public static final UniqueKey<ClubRecord> KEY_CLUB_SLUG = UniqueKeys0.KEY_CLUB_SLUG;
    public static final UniqueKey<ClubAccountRecord> KEY_CLUB_ACCOUNT_ID = UniqueKeys0.KEY_CLUB_ACCOUNT_ID;
    public static final UniqueKey<ClubAccountRecord> KEY_CLUB_ACCOUNT_ACCOUNT_ID = UniqueKeys0.KEY_CLUB_ACCOUNT_ACCOUNT_ID;
    public static final UniqueKey<ClubProfileRecord> KEY_CLUB_PROFILE_ID = UniqueKeys0.KEY_CLUB_PROFILE_ID;
    public static final UniqueKey<JumpRecord> KEY_JUMP_ID = UniqueKeys0.KEY_JUMP_ID;
    public static final UniqueKey<PilotActivityParticipationRecord> KEY_PILOT_ACTIVITY_PARTICIPATION_ID = UniqueKeys0.KEY_PILOT_ACTIVITY_PARTICIPATION_ID;
    public static final UniqueKey<PilotActivityParticipationRecord> KEY_PILOT_ACTIVITY_PARTICIPATION_ACCOUNT_ID = UniqueKeys0.KEY_PILOT_ACTIVITY_PARTICIPATION_ACCOUNT_ID;
    public static final UniqueKey<PlaneRecord> KEY_PLANE_ID = UniqueKeys0.KEY_PLANE_ID;
    public static final UniqueKey<ProfileRecord> KEY_PROFILE_ID = UniqueKeys0.KEY_PROFILE_ID;
    public static final UniqueKey<SessionRecord> KEY_SESSION_ID = UniqueKeys0.KEY_SESSION_ID;
    public static final UniqueKey<SessionRecord> KEY_SESSION_TOKEN = UniqueKeys0.KEY_SESSION_TOKEN;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ActivityRecord, ClubRecord> FK_ACTIVITY_CLUB_ID = ForeignKeys0.FK_ACTIVITY_CLUB_ID;
    public static final ForeignKey<ActivityParticipationRecord, AccountRecord> FK_ACTIVITY_PARTICIPATION_ACCOUNT_ID = ForeignKeys0.FK_ACTIVITY_PARTICIPATION_ACCOUNT_ID;
    public static final ForeignKey<ActivityParticipationRecord, ActivityRecord> FK_ACTIVITY_PARTICIPATION_ACTIVITY_ID = ForeignKeys0.FK_ACTIVITY_PARTICIPATION_ACTIVITY_ID;
    public static final ForeignKey<ClubAccountRecord, ClubRecord> FK_CLUB_ACCOUNT_CLUB_ID = ForeignKeys0.FK_CLUB_ACCOUNT_CLUB_ID;
    public static final ForeignKey<ClubAccountRecord, AccountRecord> FK_CLUB_ACCOUNT_ACCOUNT_ID = ForeignKeys0.FK_CLUB_ACCOUNT_ACCOUNT_ID;
    public static final ForeignKey<ClubProfileRecord, ClubRecord> FK_CLUB_PROFILE_CLUB = ForeignKeys0.FK_CLUB_PROFILE_CLUB;
    public static final ForeignKey<JumpRecord, AccountRecord> FK_JUMP_ACCOUNT_ID = ForeignKeys0.FK_JUMP_ACCOUNT_ID;
    public static final ForeignKey<JumpRecord, ActivityRecord> FK_JUMP_ACTIVITY_ID = ForeignKeys0.FK_JUMP_ACTIVITY_ID;
    public static final ForeignKey<PilotActivityParticipationRecord, AccountRecord> FK_PILOT_ACTIVITY_PARTICIPATION_ACCOUNT_ID = ForeignKeys0.FK_PILOT_ACTIVITY_PARTICIPATION_ACCOUNT_ID;
    public static final ForeignKey<PilotActivityParticipationRecord, ActivityRecord> FK_PILOT_ACTIVITY_PARTICIPATION_ACTIVITY_ID = ForeignKeys0.FK_PILOT_ACTIVITY_PARTICIPATION_ACTIVITY_ID;
    public static final ForeignKey<PilotActivityParticipationRecord, PlaneRecord> FK_PILOT_ACTIVITY_PARTICIPATION_PLANE_ID = ForeignKeys0.FK_PILOT_ACTIVITY_PARTICIPATION_PLANE_ID;
    public static final ForeignKey<PlaneRecord, ClubRecord> FK_PLANE_CLUB_ID = ForeignKeys0.FK_PLANE_CLUB_ID;
    public static final ForeignKey<ProfileRecord, AccountRecord> FK_PROFILE_ACCOUNT = ForeignKeys0.FK_PROFILE_ACCOUNT;
    public static final ForeignKey<SessionRecord, AccountRecord> FK_SESSION_ACCOUNT = ForeignKeys0.FK_SESSION_ACCOUNT;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AccountRecord, Long> IDENTITY_ACCOUNT = Internal.createIdentity(Account.ACCOUNT, Account.ACCOUNT.ID);
        public static Identity<ActivityRecord, Long> IDENTITY_ACTIVITY = Internal.createIdentity(Activity.ACTIVITY, Activity.ACTIVITY.ID);
        public static Identity<ActivityParticipationRecord, Long> IDENTITY_ACTIVITY_PARTICIPATION = Internal.createIdentity(ActivityParticipation.ACTIVITY_PARTICIPATION, ActivityParticipation.ACTIVITY_PARTICIPATION.ID);
        public static Identity<ClubRecord, Long> IDENTITY_CLUB = Internal.createIdentity(Club.CLUB, Club.CLUB.ID);
        public static Identity<ClubAccountRecord, Long> IDENTITY_CLUB_ACCOUNT = Internal.createIdentity(ClubAccount.CLUB_ACCOUNT, ClubAccount.CLUB_ACCOUNT.ID);
        public static Identity<ClubProfileRecord, Long> IDENTITY_CLUB_PROFILE = Internal.createIdentity(ClubProfile.CLUB_PROFILE, ClubProfile.CLUB_PROFILE.ID);
        public static Identity<JumpRecord, Long> IDENTITY_JUMP = Internal.createIdentity(Jump.JUMP, Jump.JUMP.ID);
        public static Identity<PilotActivityParticipationRecord, Long> IDENTITY_PILOT_ACTIVITY_PARTICIPATION = Internal.createIdentity(PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION, PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION.ID);
        public static Identity<PlaneRecord, Long> IDENTITY_PLANE = Internal.createIdentity(Plane.PLANE, Plane.PLANE.ID);
        public static Identity<ProfileRecord, Long> IDENTITY_PROFILE = Internal.createIdentity(Profile.PROFILE, Profile.PROFILE.ID);
        public static Identity<SessionRecord, Long> IDENTITY_SESSION = Internal.createIdentity(Session.SESSION, Session.SESSION.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountRecord> KEY_ACCOUNT_ID = Internal.createUniqueKey(Account.ACCOUNT, "KEY_account_id", Account.ACCOUNT.ID);
        public static final UniqueKey<AccountRecord> KEY_ACCOUNT_USERNAME = Internal.createUniqueKey(Account.ACCOUNT, "KEY_account_username", Account.ACCOUNT.USERNAME);
        public static final UniqueKey<ActivityRecord> KEY_ACTIVITY_ID = Internal.createUniqueKey(Activity.ACTIVITY, "KEY_activity_id", Activity.ACTIVITY.ID);
        public static final UniqueKey<ActivityRecord> KEY_ACTIVITY_TOKEN = Internal.createUniqueKey(Activity.ACTIVITY, "KEY_activity_token", Activity.ACTIVITY.TOKEN);
        public static final UniqueKey<ActivityParticipationRecord> KEY_ACTIVITY_PARTICIPATION_ID = Internal.createUniqueKey(ActivityParticipation.ACTIVITY_PARTICIPATION, "KEY_activity_participation_id", ActivityParticipation.ACTIVITY_PARTICIPATION.ID);
        public static final UniqueKey<ActivityParticipationRecord> KEY_ACTIVITY_PARTICIPATION_ACCOUNT_ID = Internal.createUniqueKey(ActivityParticipation.ACTIVITY_PARTICIPATION, "KEY_activity_participation_account_id", ActivityParticipation.ACTIVITY_PARTICIPATION.ACCOUNT_ID, ActivityParticipation.ACTIVITY_PARTICIPATION.ACTIVITY_ID);
        public static final UniqueKey<ClubRecord> KEY_CLUB_ID = Internal.createUniqueKey(Club.CLUB, "KEY_club_id", Club.CLUB.ID);
        public static final UniqueKey<ClubRecord> KEY_CLUB_SLUG = Internal.createUniqueKey(Club.CLUB, "KEY_club_slug", Club.CLUB.SLUG);
        public static final UniqueKey<ClubAccountRecord> KEY_CLUB_ACCOUNT_ID = Internal.createUniqueKey(ClubAccount.CLUB_ACCOUNT, "KEY_club_account_id", ClubAccount.CLUB_ACCOUNT.ID);
        public static final UniqueKey<ClubAccountRecord> KEY_CLUB_ACCOUNT_ACCOUNT_ID = Internal.createUniqueKey(ClubAccount.CLUB_ACCOUNT, "KEY_club_account_account_id", ClubAccount.CLUB_ACCOUNT.ACCOUNT_ID, ClubAccount.CLUB_ACCOUNT.CLUB_ID);
        public static final UniqueKey<ClubProfileRecord> KEY_CLUB_PROFILE_ID = Internal.createUniqueKey(ClubProfile.CLUB_PROFILE, "KEY_club_profile_id", ClubProfile.CLUB_PROFILE.ID);
        public static final UniqueKey<JumpRecord> KEY_JUMP_ID = Internal.createUniqueKey(Jump.JUMP, "KEY_jump_id", Jump.JUMP.ID);
        public static final UniqueKey<PilotActivityParticipationRecord> KEY_PILOT_ACTIVITY_PARTICIPATION_ID = Internal.createUniqueKey(PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION, "KEY_pilot_activity_participation_id", PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION.ID);
        public static final UniqueKey<PilotActivityParticipationRecord> KEY_PILOT_ACTIVITY_PARTICIPATION_ACCOUNT_ID = Internal.createUniqueKey(PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION, "KEY_pilot_activity_participation_account_id", PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION.ACCOUNT_ID, PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION.ACTIVITY_ID);
        public static final UniqueKey<PlaneRecord> KEY_PLANE_ID = Internal.createUniqueKey(Plane.PLANE, "KEY_plane_id", Plane.PLANE.ID);
        public static final UniqueKey<ProfileRecord> KEY_PROFILE_ID = Internal.createUniqueKey(Profile.PROFILE, "KEY_profile_id", Profile.PROFILE.ID);
        public static final UniqueKey<SessionRecord> KEY_SESSION_ID = Internal.createUniqueKey(Session.SESSION, "KEY_session_id", Session.SESSION.ID);
        public static final UniqueKey<SessionRecord> KEY_SESSION_TOKEN = Internal.createUniqueKey(Session.SESSION, "KEY_session_token", Session.SESSION.TOKEN);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ActivityRecord, ClubRecord> FK_ACTIVITY_CLUB_ID = Internal.createForeignKey(fi.morabotti.skydive.db.Keys.KEY_CLUB_ID, Activity.ACTIVITY, "fk_activity_club_id", Activity.ACTIVITY.CLUB_ID);
        public static final ForeignKey<ActivityParticipationRecord, AccountRecord> FK_ACTIVITY_PARTICIPATION_ACCOUNT_ID = Internal.createForeignKey(fi.morabotti.skydive.db.Keys.KEY_ACCOUNT_ID, ActivityParticipation.ACTIVITY_PARTICIPATION, "fk_activity_participation_account_id", ActivityParticipation.ACTIVITY_PARTICIPATION.ACCOUNT_ID);
        public static final ForeignKey<ActivityParticipationRecord, ActivityRecord> FK_ACTIVITY_PARTICIPATION_ACTIVITY_ID = Internal.createForeignKey(fi.morabotti.skydive.db.Keys.KEY_ACTIVITY_ID, ActivityParticipation.ACTIVITY_PARTICIPATION, "fk_activity_participation_activity_id", ActivityParticipation.ACTIVITY_PARTICIPATION.ACTIVITY_ID);
        public static final ForeignKey<ClubAccountRecord, ClubRecord> FK_CLUB_ACCOUNT_CLUB_ID = Internal.createForeignKey(fi.morabotti.skydive.db.Keys.KEY_CLUB_ID, ClubAccount.CLUB_ACCOUNT, "fk_club_account_club_id", ClubAccount.CLUB_ACCOUNT.CLUB_ID);
        public static final ForeignKey<ClubAccountRecord, AccountRecord> FK_CLUB_ACCOUNT_ACCOUNT_ID = Internal.createForeignKey(fi.morabotti.skydive.db.Keys.KEY_ACCOUNT_ID, ClubAccount.CLUB_ACCOUNT, "fk_club_account_account_id", ClubAccount.CLUB_ACCOUNT.ACCOUNT_ID);
        public static final ForeignKey<ClubProfileRecord, ClubRecord> FK_CLUB_PROFILE_CLUB = Internal.createForeignKey(fi.morabotti.skydive.db.Keys.KEY_CLUB_ID, ClubProfile.CLUB_PROFILE, "fk_club_profile_club", ClubProfile.CLUB_PROFILE.CLUB_ID);
        public static final ForeignKey<JumpRecord, AccountRecord> FK_JUMP_ACCOUNT_ID = Internal.createForeignKey(fi.morabotti.skydive.db.Keys.KEY_ACCOUNT_ID, Jump.JUMP, "fk_jump_account_id", Jump.JUMP.ACCOUNT_ID);
        public static final ForeignKey<JumpRecord, ActivityRecord> FK_JUMP_ACTIVITY_ID = Internal.createForeignKey(fi.morabotti.skydive.db.Keys.KEY_ACTIVITY_ID, Jump.JUMP, "fk_jump_activity_id", Jump.JUMP.ACTIVITY_ID);
        public static final ForeignKey<PilotActivityParticipationRecord, AccountRecord> FK_PILOT_ACTIVITY_PARTICIPATION_ACCOUNT_ID = Internal.createForeignKey(fi.morabotti.skydive.db.Keys.KEY_ACCOUNT_ID, PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION, "fk_pilot_activity_participation_account_id", PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION.ACCOUNT_ID);
        public static final ForeignKey<PilotActivityParticipationRecord, ActivityRecord> FK_PILOT_ACTIVITY_PARTICIPATION_ACTIVITY_ID = Internal.createForeignKey(fi.morabotti.skydive.db.Keys.KEY_ACTIVITY_ID, PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION, "fk_pilot_activity_participation_activity_id", PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION.ACTIVITY_ID);
        public static final ForeignKey<PilotActivityParticipationRecord, PlaneRecord> FK_PILOT_ACTIVITY_PARTICIPATION_PLANE_ID = Internal.createForeignKey(fi.morabotti.skydive.db.Keys.KEY_PLANE_ID, PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION, "fk_pilot_activity_participation_plane_id", PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION.PLANE_ID);
        public static final ForeignKey<PlaneRecord, ClubRecord> FK_PLANE_CLUB_ID = Internal.createForeignKey(fi.morabotti.skydive.db.Keys.KEY_CLUB_ID, Plane.PLANE, "fk_plane_club_id", Plane.PLANE.CLUB_ID);
        public static final ForeignKey<ProfileRecord, AccountRecord> FK_PROFILE_ACCOUNT = Internal.createForeignKey(fi.morabotti.skydive.db.Keys.KEY_ACCOUNT_ID, Profile.PROFILE, "fk_profile_account", Profile.PROFILE.ACCOUNT_ID);
        public static final ForeignKey<SessionRecord, AccountRecord> FK_SESSION_ACCOUNT = Internal.createForeignKey(fi.morabotti.skydive.db.Keys.KEY_ACCOUNT_ID, Session.SESSION, "fk_session_account", Session.SESSION.ACCOUNT_ID);
    }
}
