/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.skydive.db;


import fi.morabotti.skydive.db.tables.Account;
import fi.morabotti.skydive.db.tables.Session;
import fi.morabotti.skydive.db.tables.records.AccountRecord;
import fi.morabotti.skydive.db.tables.records.SessionRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AccountRecord, Long> IDENTITY_ACCOUNT = Identities0.IDENTITY_ACCOUNT;
    public static final Identity<SessionRecord, Long> IDENTITY_SESSION = Identities0.IDENTITY_SESSION;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> KEY_ACCOUNT_ID = UniqueKeys0.KEY_ACCOUNT_ID;
    public static final UniqueKey<AccountRecord> KEY_ACCOUNT_USERNAME = UniqueKeys0.KEY_ACCOUNT_USERNAME;
    public static final UniqueKey<SessionRecord> KEY_SESSION_ID = UniqueKeys0.KEY_SESSION_ID;
    public static final UniqueKey<SessionRecord> KEY_SESSION_TOKEN = UniqueKeys0.KEY_SESSION_TOKEN;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<SessionRecord, AccountRecord> FK_SESSION_ACCOUNT = ForeignKeys0.FK_SESSION_ACCOUNT;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AccountRecord, Long> IDENTITY_ACCOUNT = Internal.createIdentity(Account.ACCOUNT, Account.ACCOUNT.ID);
        public static Identity<SessionRecord, Long> IDENTITY_SESSION = Internal.createIdentity(Session.SESSION, Session.SESSION.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountRecord> KEY_ACCOUNT_ID = Internal.createUniqueKey(Account.ACCOUNT, "KEY_account_id", Account.ACCOUNT.ID);
        public static final UniqueKey<AccountRecord> KEY_ACCOUNT_USERNAME = Internal.createUniqueKey(Account.ACCOUNT, "KEY_account_username", Account.ACCOUNT.USERNAME);
        public static final UniqueKey<SessionRecord> KEY_SESSION_ID = Internal.createUniqueKey(Session.SESSION, "KEY_session_id", Session.SESSION.ID);
        public static final UniqueKey<SessionRecord> KEY_SESSION_TOKEN = Internal.createUniqueKey(Session.SESSION, "KEY_session_token", Session.SESSION.TOKEN);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<SessionRecord, AccountRecord> FK_SESSION_ACCOUNT = Internal.createForeignKey(fi.morabotti.skydive.db.Keys.KEY_ACCOUNT_ID, Session.SESSION, "fk_session_account", Session.SESSION.ACCOUNT_ID);
    }
}
