/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.skydive.db;


import fi.morabotti.skydive.db.tables.Account;
import fi.morabotti.skydive.db.tables.Activity;
import fi.morabotti.skydive.db.tables.ActivityParticipation;
import fi.morabotti.skydive.db.tables.Club;
import fi.morabotti.skydive.db.tables.ClubAccount;
import fi.morabotti.skydive.db.tables.ClubProfile;
import fi.morabotti.skydive.db.tables.Jump;
import fi.morabotti.skydive.db.tables.PilotActivityParticipation;
import fi.morabotti.skydive.db.tables.Plane;
import fi.morabotti.skydive.db.tables.Profile;
import fi.morabotti.skydive.db.tables.Session;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>account</code>.
     */
    public static final Account ACCOUNT = fi.morabotti.skydive.db.tables.Account.ACCOUNT;

    /**
     * The table <code>activity</code>.
     */
    public static final Activity ACTIVITY = fi.morabotti.skydive.db.tables.Activity.ACTIVITY;

    /**
     * The table <code>activity_participation</code>.
     */
    public static final ActivityParticipation ACTIVITY_PARTICIPATION = fi.morabotti.skydive.db.tables.ActivityParticipation.ACTIVITY_PARTICIPATION;

    /**
     * The table <code>club</code>.
     */
    public static final Club CLUB = fi.morabotti.skydive.db.tables.Club.CLUB;

    /**
     * The table <code>club_account</code>.
     */
    public static final ClubAccount CLUB_ACCOUNT = fi.morabotti.skydive.db.tables.ClubAccount.CLUB_ACCOUNT;

    /**
     * The table <code>club_profile</code>.
     */
    public static final ClubProfile CLUB_PROFILE = fi.morabotti.skydive.db.tables.ClubProfile.CLUB_PROFILE;

    /**
     * The table <code>jump</code>.
     */
    public static final Jump JUMP = fi.morabotti.skydive.db.tables.Jump.JUMP;

    /**
     * The table <code>pilot_activity_participation</code>.
     */
    public static final PilotActivityParticipation PILOT_ACTIVITY_PARTICIPATION = fi.morabotti.skydive.db.tables.PilotActivityParticipation.PILOT_ACTIVITY_PARTICIPATION;

    /**
     * The table <code>plane</code>.
     */
    public static final Plane PLANE = fi.morabotti.skydive.db.tables.Plane.PLANE;

    /**
     * The table <code>profile</code>.
     */
    public static final Profile PROFILE = fi.morabotti.skydive.db.tables.Profile.PROFILE;

    /**
     * The table <code>session</code>.
     */
    public static final Session SESSION = fi.morabotti.skydive.db.tables.Session.SESSION;
}
