/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.skydive.db;


import fi.morabotti.skydive.db.tables.Account;
import fi.morabotti.skydive.db.tables.Session;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>account</code>.
     */
    public static final Account ACCOUNT = fi.morabotti.skydive.db.tables.Account.ACCOUNT;

    /**
     * The table <code>session</code>.
     */
    public static final Session SESSION = fi.morabotti.skydive.db.tables.Session.SESSION;
}
