import React from 'react'

export const DummyComponent = () => {
  return (
    <div>
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
      Dummy component<br />
    </div>
  )
}
